apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fabric-cards-apic-client-ids
  namespace: fabric-services-cde-preprod
spec:
  encryptedData:
    SPEC_CTM_CLIENTID: AgCxZ3Z6jra7BXTCU8ORrTDCyCUKSrT+kS34PyRQydy0lWKS/743mT2TBt7La8rIcTSQUWktqMYbugVI7XYvctCd3E3YJmLVs+W48OqdZW2pGbEOCYm3nQApFmaY+7tsFh0iRDJ+CEVNnyn4nHu0Lot7f3br8W9j8oRZVdcm/wBkJ0ucWoWpO4mocv8y5Fd8taOzo9HhcfFhmaKO4IDZeadUrAUUOJ39thATZiB2e9UOMVS7wQ+kdbz45LEhNIg/0VYiQGfE2HJq+/+SM+Zo89Op73anTiVdVe8qXLYCVWIqflb2vydoMVNxhC4pL+/K7i+tcudquzK7o+t687hzXhYsPzK5n4qGVXWZG6WHrdU4D9IWHFEtCpY/shzk9HdYfu2MFlykxgq6UluKstBQe3CPCtUFa3fBuIPceoiVX1yZIbdJnX02kSLtbrstDkx9zjsIX/AfSQ890cdAmhj2NEHcYZp5gfjwmLHjDT/QH8Wkjx3fwMQqcpZ9GZikbEoNPq01thxQ/y3SL9k+P5lw/4czLWgv4aCt2SNVFAd54dMaVOn8OiFNqSji/JQayO+LjmAsk+HblkV2Q+fAWVtvl/G73KuWZNM+1nwT4hWMtnWgcQ7zPrDTYKGetbTmzIhffB+4zqg0oCEu67F9bWlOfF2TXuDWdb79IVn3G+10vt8lsF15Q9Fvw+j+QCZgb358ruoaPtUAr0zfHIxn8OC9c1TBLdmmoHaarKdpcw4tHSjZL3UX744=
    SPEC_ECHIDNA_CLIENTID: AgCjqcyUyYRYhn0pzifcttj9VPvfrjvazhl24oRw/THpopTGzX+JFPjNDA5NqXFgQJqcvKkQBbxtmN7ei75ZfmGMriLk5UuTLzIbGiJw5xJ+YhPwgZGD8Od4WwbZ8yJzLoShSk63L0zFVABozuTUEbTLMVIQK9iYLaL6ETuzxdenm23WiYcnmLwKO9wgIYz1VmmN7QooeF3g1DJOo7LPgAaKNfCSvHrHZoDNJl61PrH9wMP5hAzSXfTQC/AqFjqb6FpO4hn0cuQwRsEfpNxOsdKUo82DNd0IeHwTh2kBAn61LRr9Xyh40lXGS6h2rqihAl0IQOuUEPylkiCIsj0HcskFL8v9pxAdw/8v1xMBIpppY4R+deFai10zogHxopJXYIWmSsP2FnpRlscQwIMdIGmHt3+QIIUIKEB627QQkPdRI/wn+NYTq1Yg9pavTBhzb7eDYYpB+Od6MmTl9GaOJNZ/X9QKqjoID2Au00D8ctY/NyjXajbRhtZhoF1KzRskxQb/3aHW+YdUhjGPezFe41EKUitMxlG0NL5XKZuO+L+u9pMLR24KgiscZ1kXj6luXkYXX3cIzb6Bzooimw4aiwidzskVT7tcrQkiws8I5kpI+jXWwVWxd9+L2hge/mPsk9hddDo9iEmQ1RyGUxvSN34clBumTKZuYd0oE7yM4eNIeMHltKX285CzUzR2NJgTlinEcl0dY/uXb0P7R6Dxfed24xAGkSHX5PJvE5KdJpGx4ZyQlX8=
  template:
    metadata:
      creationTimestamp: null
      name: fabric-cards-apic-client-ids
      namespace: fabric-services-cde-preprod

