apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fabric-cardcontrols-apic-client-ids
  namespace: fabric-services-cde-sit-n
spec:
  encryptedData:
    SPEC_CTM_CLIENTID: AgCJQtfyfngOMdDs5PErDhUSLx8AOzGStes9/5ZwLGRJC/92QQrBCHRS626GPokLRHzZp1hqoXj8Vt2mwLCqvuMFEfHYzwSXuFJI/Pfcy1vXkAx2dEBmYmh96P+WAmyBV1xNH77qjCRExUiINDYQlQucSFx/PC0rCAXx30XPKyv6wWzT+5HTpU4lkxl8ikJPUlG8+y9wKByDMYXbtTGTBtqbQZjFLqdPEimhAkGXEi3dUxdwnYkkjq1McjEv+wp2Xw3IN+/E/0y/cLPStQfQYQ5Ogq/IZAng97quuY8L5VwBt6SjEQqfS5r323e8d7r1XhhP2u0akiVGyuyN0FExybvUB2ZnZpFpNEyCKEivNHh2FuhmZbnutImp7b/bEqhwwPjUep+i8pIvSKK5Zid6Kml+ZR+MG38vEt66lmR+CYcdirqae1EzlY6RLB92rdYU+F1pVlEJqif1IqmjOkcMErm1TubToiUvW55ZuhJDM0izhO4N/ilzUrbBlv6WT+7bSwtrzPcNHskE7Eb+EUv477tQlaPkCoYPnSLCXxScozRLCD42yJl8eao30KbQfBHrZp5ESiR06pzTonQcL1te+SePfUF0AAXTr7lMZVXqTC+GeeFde4Aa+0LGpzO586be9YzhtXfLX4nfZwqQWH+S5j0VwxkCHeuQYz6OQjgoA5JZgXH6Ayoc9VJXvbw9AVcv8K3njdLlIq9qrJaIzyEIkwuZyGmDi2/z1N3zKXHRB4MFsD/7W7s=
    SPEC_VISA_CLIENTID: AgCC16303isv7Ywp8QkBzyNDXWH9aKzUo8i1fSQBXOYsW2aNC5HucS67IccrDLF8641qn2cQO3qKeOtCFEUIyUkxQG02o9NPA9pDG3E4uJFr7rQdZym/m7ApzjxsKSOBxGva5Dyxli2xDxHFhrw2fo/HaAYuR0zbNT9/ui6ID6dXONvkv0ssHoUFJY4YQmxuKJCLlizKYSdKdIByQmGIFSU2HgPdr6jAodHm4zVwCrSCnd2MdKgqNmMX47uJ7oClLnMbiCagFQl/YIQpWKYNMcBqNiBgaICNi6rXpB5fODu/2niqsNbf3EMHuDxYsTb8BDDxEI26VYv30Lrad8hGT2+oIVoEJJfQ6Kd3By7NMFOkDjxt0PlPyYlrY7Nftvs9HsHxwl0mA5bJ5OfvyrXPwokvdxeweFkdcL4YS8/YhZvIOS0JCPbq3zbcFzeM16VZbOnfR4RTJVfGswtKkV4f9lKYnRt1WNYrpkK419+MuptDsk6D1/zMv409O4y9LZZ2P6oahW//JMdd9qHcSbxTGLeBFjOGo0o/UAHjN51RzWHuGyPo4rtEBA5jhcL/cG3DjvRVtGNP3pLw+FHK6uaRDqMDXXUzEjg8jjLrUQXMBToujzZE0/Bho0yvlrkFMrG/DDrEV7gk9nrP6AEJGigcP0cQl2Hwe8tkC6HnTbq3c9gm/dAeE3zLBj4Ae8XoUSL2nV0+dlCJOt8sZ9gooSBJHz3mDLduzYMyrFTLjy61/NjjjDyR0h0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fabric-cardcontrols-apic-client-ids
      namespace: fabric-services-cde-sit-n

