apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fabric-cardcontrols-apic-client-ids
  namespace: fabric-services-cde-intpnv
spec:
  encryptedData:
    SPEC_CTM_CLIENTID: AgCKrwkk10AwlpIO8wqM2UFgMFzMq3ZABxKdgPM73Luqesdk85DuxoLCNnySU8myFYvw/Z8lCzvJBT1sCQ8t2yBmYmMAz5qUc7hg3FrYtRe+ll4p0L+y45eM/zYEJd/RzSrh59AjhYg0Sb0g+YRg3A0aeqOGs+Lg/Mn9sA9bDa4NKiJm8gYwQbdtjjC51LFHaMNn1nbNKLtlFHi2yHpp7UDq/7LnEgZ/uVwZlrlNc31mEr5N8BM5b3peIsYpcDqY4SUdvURc9GYDQMyaIy588fAsMHZ3RVmZmACGI2AtRqZtIvctv0Zfmf2N8mgpRr18oi0oNh/dNiEc2o4LDKHDkaS1pvhxSB6jCGetE6cqcv5dvdSw8lbTRdhwapQv+4lNAytU5mQywwqXJsD1IdTDZIxHEzNvGEgJAK27/AI3s9K3gNYT2pRu2R4HsM561mJYXvD6nmoqae7GsO/HVLrRszPJQ6PoxszCAAYktm52POyYlkXtYUQKrYJu3WMX/bazNoToE89a7mhL+zB8gTHn0lJ/Ud4EqsHAHnDGKvEdybpZb5hIwNwOkG8SmLGNX7V3m7cM/U6jOTq5i2ch35jlxKUkJnHtx2QwCozPbvUFm1OWLI+E2cHKHmbufacOprncDDU7uFTKh1caKtUW1rQb3R5v67XLOa4q4QaUpmEo5FuR+1N71GyNo4fjSQ7l0t42REjo9IijddveZvsdeI9TcRyZMJL6unOEIW5uZUuVoiPSr07ZDRE=
    SPEC_VISA_CLIENTID: AgCH7BnnEWpl+m6CuBqZVg7egK0dpn+gNgY9rgz7KMe5jwJGR8zhK860dHLbiqcIEzIIv27Ot7mccg45fHab/ZmyOASnpLdoEgM1HteDHcxFKJpa6R1UaSRo75tdJqCBMgynCB2EJCtwDBcRw4AXPAWgXsxJpaJFWk3K1kG5YBELZT5zWDi2jcbjtRi1UfB2mtklcwGHGv6ihjUEsI1LO1rDZhKQWvB1wcV7YzTZlLEh1vWicebJDyK7x31MZEdVu6ZL1HLkWFkffuHB7DGkag3Pa+Cj+4fbBzqRvN0vp0RNajhJjfzzNICdr9auVUMHkDQMBnVLrp67IKsB6Ks9vCWHhBdubwyvU+0tlS11CL2K9XvdasPcHjp0mshyNvxsrHJkw1A7aZtRD2kxJJl502fg0GHLew6Pes1uQZG2izAV647hOJdcfAC6GaMoWswXcv/wMJVLVhZfa3DGFB0MYnG0qvBc6sGmjOj5wiDa/zvCQF/ZzHiRqxD3T/AyoXNer2zejbNYS4kfFMonB93vWkhFxIo4IeHGKYCJ0R6rDIbIu792RHtD0ZVcTNuwXqtGZIJ0gzJlg9cVK5Elctc/SkOMifeONb+RB0WHyHVzn0VAgYXvPqDaPcCQ6dX7Uo7HG4XwuHCLWA/rdWDIbPm5DMSPcpFsJOHBl8hl4ty8T/OW7FLLugHGLJI+KgNpP6WfkZ5iD4svCoo4rVPnasgAYdvVPTNGo2GbdD0gYfrp84DbtvyCBSE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fabric-cardcontrols-apic-client-ids
      namespace: fabric-services-cde-intpnv

