---
# Source: catalog-info/templates/catalog-info.yaml
# This file is managed via anzx/fabric-actions. Do not copy or edit this file directly.
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cards
  description: Cards - An interface for Card Activation, Select PIN & Replacement. Provides a powerful and convenient way for cardholders to track and manage all payment activity on enrolled accounts and tokens
  tags:
    - golang
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: venugosv/cards
spec:
  type: service
  owner: venugosv
  lifecycle: production
---
