site_name: Engineering Specs
site_url: https://archspecs.com/
repo_url: https://github.com/venugosv/cards
nav:
    - Overview: index.md
    - Architecture: https://github.com/venugosv/architecture/blob/main/docs/DCVV2.md
    - Dev Manual: developer-manual.md
    - Integration:
        - Audit Log: integration/audit-log.md
        - CTM: integration/ctm.md
        - Echidna: integration/echidna.md
        - ADP Vault: integration/vault.md
    - Non-Functionals: nfr.md
    - Design:
      - DCVV2 : Design/dcvv2.md
    - Run Book: run-book.md
    - Tech Principles: tech-principles.md
    - Security: security-policy-datacontrols.md
theme:
    name: material
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "_"
    - plantuml_markdown:
plugins:
  - search
  - techdocs-core
  - kroki
