apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fabric-callback-apic-ids
  namespace: fabric-services-cde-sit-k
spec:
  encryptedData:
    SPEC_CTM_CLIENTID: AgB6OyR4Gy9sl4ZDgNN5xWyHhd0oZ+4ANCDx7cTASMenkTprVVKcmIm/GXSB6VGboCKZjLiPG4xwd5m5jup5+Tjri9Cv89JxX+RABR4/cGzEhPCahhAaRAuAX1KyoRQywj2vfnM5LicoPHC9M4PGKAdNIREemb3Q/gnXCgWGa6+aYGN5tbcZco3L/IrUAG2Hh61cijnh6bG47VCjHY5G0A1/aM2u5iqqU/mLSiur5JsVHyye0ffl+LsucFF+gZoDyx4dcQTdD0C1zkyVs/v+YN2kdwMqeWkVPmgeGhIs083rBH7OUwAO6zCeV4QdsKSPlmLZPMZxiKJ2iJ3gyNs1iBoYVUHU4NwK+LWlj5L04F4M+Bjth2U3ZI4ZI+mNaYsXq1epQVEBJBPSWZMapYK/W+f5elxCORfNef8DdjR6oCT/sZwtbnKKT/b6yjyOSAljCBVaiLxfYlYsaGOKDkwR//RsPa1FWN7Eo58qwn/gprdPgjiPJmqRUSHKcWpHsLfZwzSvjTWCeFui+uIN98E8aolDoMgY++ejYhQKQIdNwlTq4IEIBKP1t95jm+f4/JallGJdcm9S/BR62e2gjFl3PFfpWZcsPdsCWJOALgU4974Y+AJUOgWJGiFAmaDqOq2M5HuEy/qnN9xzDf4nGqFC7ELkdmDHd4/aSHe6D/yElimFE7pmSRrPBo1B0EdAAb3sdasNlAxvx4iocH4oxLO2PaKWlsLWu56Rw810eNyjmLKviH96NY4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fabric-callback-apic-ids
      namespace: fabric-services-cde-sit-k

