---
ops:
  opentelemetry:
    exporters:
      stackdriver:
        projectID: anz-x-fabric-prod-d8873d
    metrics:
      exporter: collector
    trace:
      exporter: stackdriver
  port: 8082
spec:
  apcam:
    baseURL: http://api.ecom.apps.anz/ap-cam
    clientIDEnvKey: projects/791972436961/secrets/apic-ecom-client-id-prod/versions/latest
    maxRetries: 3
  auditlog:
    domain: fabric.gcp.anz
    name: fabric-cards
    provider: fabric
    pubsub:
      projectID: anz-x-cosmos-prod-ccc3bd
      topicID: cosmos-audit
  auth:
    issuers:
      - cacheTTL: 30m
        jwksUrl: https://identity-services-prod-int-gw.apps-int.x.gcp.anz/am/oauth2/system/connect/jwk_uri
        name: https://identity-services-prod-int-gw.apps-int.x.gcp.anz/am/oauth2/system
      - cacheTTL: 30m
        jwksUrl: https://identity-services-prod-int-gw.apps-int.x.gcp.anz/am/oauth2/customer/connect/jwk_uri
        name: https://identity-services-prod-int-gw.apps-int.x.gcp.anz/am/oauth2/customer
  cardcontrols:
    baseURL: http://cardcontrols.fabric-services-cde-prod.svc.cluster.local:8080
  commandCentre:
    env: production
  ctm:
    baseURL: http://api.corp.apps.anz/daw
    clientIDEnvKey: projects/791972436961/secrets/apic-corp-client-id-prod/versions/latest
    maxRetries: 3
  echidna:
    baseURL: http://api.ecom.apps.anz/ca
    clientIDEnvKey: projects/791972436961/secrets/apic-ecom-client-id-prod/versions/latest
    maxRetries: 3
  eligibility:
    baseURL: http://cards.fabric-services-cde-prod.svc.cluster.local:8080
  entitlements:
    baseURL: http://entitlements.fabric-services-prod.svc.cluster.local:8080
  forgerock:
    baseURL: https://identity-services-prod-int-gw.apps-int.x.gcp.anz
    clientID: fabric-cards
    clientSecretKey: projects/791972436961/secrets/cards-forgerock-secret-prod/versions/latest
  gpay:
    apiKeyKey: projects/791972436961/secrets/wallet-visa-api-key-prod/versions/latest
    sharedSecretKey: projects/791972436961/secrets/wallet-visa-shared-secret-prod/versions/latest
  featureToggles:
    features:
      - REASON_LOST: true
      - REASON_STOLEN: true
      - REASON_DAMAGED: true
      - PIN_CHANGE_COUNT: true
      - DCVV2: true
      - FORGEROCK_SYSTEM_LOGIN: true
    rpc:
      - /fabric.service.card.v1beta1.cardapi/activate: true
      - /fabric.service.card.v1beta1.cardapi/audittrail: true
      - /fabric.service.card.v1beta1.cardapi/changepin: false
      - /fabric.service.card.v1beta1.cardapi/getdetails: true
      - /fabric.service.card.v1beta1.cardapi/getwrappingkey: true
      - /fabric.service.card.v1beta1.cardapi/list: true
      - /fabric.service.card.v1beta1.cardapi/replace: true
      - /fabric.service.card.v1beta1.cardapi/setpin: true
      - /fabric.service.card.v1beta1.cardapi/verifypin: false
      - /fabric.service.card.v1beta1.cardapi/resetpin: true
      - /fabric.service.eligibility.v1beta1.cardeligibilityapi/can: true
      - /fabric.service.card.v1beta1.walletapi/createapplepaymenttoken: true
      - /fabric.service.card.v1beta1.walletapi/creategooglepaymenttoken: true
  log:
    level: info
    payloadDecider:
      client:
        - /fabric.service.entitlements.v1beta1.cardentitlementsapi/getentitledcard: true
        - /fabric.service.entitlements.v1beta1.cardentitlementsapi/listentitledcards: true
        - /fabric.service.entitlements.v1beta1.entitlementscontrolapi/forcepartytolatest: true
        - /fabric.service.entitlements.v1beta1.entitlementscontrolapi/registercardtopersona: true
        - /fabric.service.eligibility.v1beta1.cardeligibilityapi/can: false
        - /fabric.service.selfservice.v1beta2.partyapi/getparty: true
        - /fabric.service.accounts.v1alpha6.accountapi/getaccountlist: true
      server:
        - /fabric.service.card.v1beta1.cardapi/activate: true
        - /fabric.service.card.v1beta1.cardapi/audittrail: false
        - /fabric.service.card.v1beta1.cardapi/changepin: false
        - /fabric.service.card.v1beta1.cardapi/getdetails: false
        - /fabric.service.card.v1beta1.cardapi/getwrappingkey: false
        - /fabric.service.card.v1beta1.cardapi/list: true
        - /fabric.service.card.v1beta1.cardapi/replace: true
        - /fabric.service.card.v1beta1.cardapi/setpin: true
        - /fabric.service.card.v1beta1.cardapi/resetpin: true
        - /fabric.service.card.v1beta1.cardapi/verifypin: false
        - /fabric.service.eligibility.v1beta1.cardeligibilityapi/can: true
  ocv:
    baseURL: http://api.corp.apps.anz/ocv
    clientIDEnvKey: projects/791972436961/secrets/apic-corp-client-id-prod/versions/latest
    maxRetries: 3
  port: 8080
  rateLimit:
    limits:
      activate:
        period: 60000000000
        rate: 3
    prefix: prod
    redis:
      addr: 10.160.2.116:6378
      secretId: projects/791972436961/secrets/memory-store-cards-prod/versions/latest
      tlsCertId: projects/791972436961/secrets/memory-store-cert-cards-prod/versions/latest
  selfService:
    baseURL: http://selfservice.fabric-services-prod.svc.cluster.local:8080
  vault:
    vaultAddress: http://eaas.adp.prd.sec.gcp.anz
    authRole: gcpiamrole-fabric-decode.common
    authPath: v1/auth/gcp-fabric
    namespace: eaas-prod
    zone: corp
    metadataAddress: http://metadata.google.internal
    tokenLifetime: 15m
    tokenErrorRetryFirstTime: 500ms
    tokenErrorRetryMaxTime: 5m
    tokenRenewBuffer: 2m
  visaGateway:
    baseURL: http://visa-gateway.fabric-services-cde-prod.svc.cluster.local:8080
    clientID: C721062A738A481B800BE5F7CC852602
