apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fabric-callback-forgerock-ids
  namespace: fabric-services-cde-preprod
spec:
  encryptedData:
    FORGEROCK_CLIENT_SECRET: AgADcU11qacTm94X1VUh3qzXktI9mdvblKVVMJx6AeglvQqoN1FCa/E2jewR3z4bANRSXK1o/ryPVn3s8Sntuozt+GDIuTM3h+T2LhgK9YRlvPN8je86dvt9nQEL0xU+VUkk2eMLEZaIbmopxRZaOmpb8vKWxCfyNgusYNPW+7TlPXe4F/NanxpJ0lYTVxqQmJPmmgqFyqBoxne0Hv+YS6QZO+YO6tC0Ob4457SIkk9UgkLrFpB3JbLSab0rvYDlVtkTQD+LyD9if7L7sEuvasgj5LeZ9b61HxRQSFpCrdj7Ra/fwsbkyUL9u+T3YDHhxfXilAuE7QFDEMBIkVUvFgIqpum7WSc1sulk+A/9FJ3kHSAxuiq3GQy72JIdD7ae2ftrD94/1mXeAw+YyO2yR7dTj/HzTNmDGBDmea27E1YcrdkT9pSQ5AIDS0GhQ4R9yjbgG+yE4175iyuPetEs844RZIMZj/pvRxTMVQM6GiRDQyXDJvSHrlfKxzZ2kFIJGHFmT8Af5zS7Wr4VpyBuk5zWlPxD6eVaQIqbiSih7hBd7eLOUwpaQVRniOKDwUVMCbZvSk7LMbeEHjiNd8267GdRMIBLCvErv/IlR1eB7h067+oiYvdpiMbNO14JDfSJx645WiXAYdAldD0pHcrHP5oAi2MzQiJK4s/pAlyodfVO56rL88UypJ2wwCmCWBnP4E9yrUNUfyzGc0sC/w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fabric-callback-forgerock-ids
      namespace: fabric-services-cde-preprod

