apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fabric-callback-fakerock-ids
  namespace: fabric-services-cde-sit-n
spec:
  encryptedData:
    FAKEROCK_CLIENT_SECRET: AgBNONSOzox4f+4nIG6avaiIt2L+fbhK+n2oaChqnk8vwcskjNdZ6c6YLXXm59ksHEuwqqzUCLykuH27eQeCTXdWMEzc+TJWbF2b7BrRS0yRPG4Lk7pZjUv1rEMMJKrjET0CJbTYrN/re0lexk7Lu6M19I9MdPK1k3MoFZxhU6j62bkNQadWxve6cqrHNoAm9koHkoD+yoVdqEHV1pZXeyCwzBQdoVshaLu6R5NDgIIQlnhu07z1yACo8bIOr2vx5LuJ5T5NLXFSsk4YXxaRpytEWrz2AHRQOX1VNH/TfHMOy6cnSncR9YZibW8OL4HKiCzkcs8KPVFxtqVT2iAwPRdNQjfeJl7VJ+Xrwq4bF50G87G2O7ebP8ZiQSeNlf5LIRPiQNa0DGqeUaYWrJABPmGShD5lN+EXrAXD/oRvbH+XUEpOyUcY0AXTIevUtgjaxvs3fwbTF/1Pv1pE7x+6MBXrWVf3oV18zDcsv7MUTmn0ZUv2xQq92ECpNmO7X1Y7/HwbT143d+ZUIVUFU5ozFix+U6X37XuGvCbXGTGFPM+KeVaemzhHAjY5dT5pjjJwXmBhopv8NM/jh3Ww6Xpx/ATyQF3n+NWXe4EIlRsWH5lTboXAi0GsmG6z8lLJPDen7nM7Gijg/2DP73M5Sd1YNMq6IHOO+VisnPG99yZYeaT2OdyBP/fINQ2BeFPd7wx1UH8MvnnD2qhl1FVPgfbc7ZgBerzsRLzGIVLjBoQtDzA/E7n8ZlI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fabric-callback-fakerock-ids
      namespace: fabric-services-cde-sit-n

