apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fabric-callback-forgerock-ids
  namespace: fabric-services-cde-st
spec:
  encryptedData:
    FORGEROCK_CLIENT_SECRET: AgCY/bC5MAxtmw1skMGzd+sTQxoF3uKFoifDxIyG5RIELcSLDj6YTjS71DDjV6SFeHpasBusiOpSKDRgTDJklJIHxsODW2XlStKnPUJwfmhZmnxNJTWvPPKf3Pwcl3jHPvCpiaaoct/Msy4+V/2rkKloUdZdbYRhZfm5nu6EcHQqDUy5r3cNwQv99ctyuFwjLxvibztwLX9gtvr3gVfJHpxPOO5uamUUJNbTYVPtL0PRDadOmhQAEf2pGIdlel3YqOgRM8Vek7dUkQIoN0UEfZzTg2b07c5JHlUzzOHwl/LTwFsk0b+5XcZyCVCBPTsS6M1HcPrYDlVtsHTctVPwxjAt7030KeKkjFXFU+ryCDEifIy05dluKSN2DDjNlyNIZFDg6TqdEpYDrrZjy5UqPZft2bJhtujyFad/d74fAaooktOnpad8SPDe8Ab77Imd9vAHRfieqtng8V3PbFAxpW/5hWRymBt2zTAjgHWDxcVtrE+LGvHkWAa//YWWPdF5GMEqkWjFcoj75Ow8maiSQzg+HsQy4eloY4lwqBZeWd82Lsz2Kut4Wz+u84o/YVPv6Igmnw6T0HsDOfIkXnOdu/KdzvtdvuPQQB5CDZLgfuGL32qg3NkIgWfN64wepwQP+W+lhdVr37u7cBs8HIhJhEZb8a7tYw3mu+NEgWbVzdDdjtMr3LFkdzptMWNRvPUADc12yCqysPlpxPK6eQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fabric-callback-forgerock-ids
      namespace: fabric-services-cde-st

