apiVersion: fabric.anz/v1alpha1
kind: FabricKubeApp
metadata:
  name: callback
  namespacePrefix: fabric-services-cde
spec:
  application:
    image:
      repository: gcr.io/anz-x-fabric-np-641432/cards/callback

envs:
  - filePath: ./config/callback/config/platform/st.yaml
  - filePath: ./config/callback/config/platform/sit.yaml
  - filePath: ./config/callback/config/platform/sit-k.yaml
  - filePath: ./config/callback/config/platform/sit-n.yaml
  - filePath: ./config/callback/config/platform/intpnv.yaml
  - filePath: ./config/callback/config/platform/pnv.yaml
  - filePath: ./config/callback/config/platform/preprod.yaml
  - filePath: ./config/callback/config/platform/preprod-k.yaml
  - filePath: ./config/callback/config/platform/prod.yaml
