apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fabric-callback-apic-ids
  namespace: fabric-services-cde-preprod-k
spec:
  encryptedData:
    SPEC_CTM_CLIENTID: AgCQhLv6ZmhL8lx5zTrDW4zEDKWxdhlJpeo29vTnvWKRi7IQ78gDWgxgN1bh+uUUabs9KqvUXZcdOB/6NoFRwpvZEVKydIQ3EOWE47zQsrq8iXjEBpV8FlFih7PyvBOt4sxxH8+NWtUSgOWHBjtmojaoecCMZBPRxxBdzlYfr7KpqRgaELLgM/8VpDY+2TflnZiemQh1dWTQ0I99aTFFt0t6FbX6uOXRDd2kPbk52MyFk+DsuRCPunOFl3d9KmFC5TKVJtRuoS0ih1wzljGWcvTfi96RQNcfD65E6+kPql198/ZnN07rDCcN5YeVpbd0JG1cXYAmbkWiYhWv2HPi9ffZ7E0lrrHrlEzc0Z0o/TkXvT0I16ADA983afMZn5/W3neS1l1/BxDTfTR4uqCpKbcsjaPnWNMB5nQ5RSMMtnQ66wNe8Ph7fbw2Kw4EVeyZbRFtwuZN5Fox4mMRhQW+qR8d87HCG1GyFtasd7a4eZXFCa1aRwu9k6GSApsBdDB0M9H9+tKqEJgMgjE+jAkWoHRm80OtQzeGMjakz3vAnH/uJLtDTDzr7o7vCBxecP8lPzoj7giWd9lAhkv2FoeYHATcN+jlE7NXtSYfOjbJmyfddbOVltiVgBQsuQPqsk4apdRMxEbgUty0jWr+rkSpfOeWezCyekFCCQ0VBvW2+Bt6PhRGIQFIxLqxwI3KICMTMDTLMHG+rPXJwHmsnLihuyKIRdC78k54MWz+9+g8YVnh02r0TOs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fabric-callback-apic-ids
      namespace: fabric-services-cde-preprod-k

