apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fabric-callback-forgerock-ids
  namespace: fabric-services-cde-preprod-k
spec:
  encryptedData:
    FORGEROCK_CLIENT_SECRET: AgCWsuWSpYLto2YhULCym9Via9Ylq3d9mdoYobRYC6N/k8ENYCGiRPBQBzg+QjmkTSnjx9uxepFlk4ZS6flO88Fiva/iPNTjyDLuL1HwKJ33xVKxyEmbSyqo0sbg5Rxxi5qHa2IAsY4nfVo12WLydKJPs4JPdtFxbcwtJ0pY0fPpxZT2LMcm0uqzNWzqkGTTkdopqMVa+JAtaVKVKr+bReBM21wmkQdOlkrbMbu/mYzIeMPiu3EuZ1A8P1LoGteL5WXPpzOq6xImM7pLtoGelyBsELVHq6/u1S6mXhkL3ubLu5ygaNDYPJBxab90qrbBVH4KEXU1YRxxrkgCEhyWdiKdpwu/3FFOgfWWpsaxkEGSNJkEuXx7+ueY+FMQhlKZXMpdKw5kK6f/9aB10rm377xKCTiIF5LiV6vKLk7b/v+uPOj6rjwN6R6ROgMti7T1ILtGvXHQ0/Ne7NOiVUzv4czqbQGgMcPt9GKgzWiGMBY2Kd4UhDDVUvd7PJnukMo5K7vAwvoyQJiq0j94eFY73qb4Q8seuzTCs2IApd7KsTawyB0M9KmAoStxEZCSoPINMHZJjwsK1XdPnCpdK7Z9IqFOnP8xFSdvnPAlzS7MqDRFjOpyH+Dqp4sBHo1xCC36polfFlHcRXCAJcQJaCDGkfm4RYhN4zxmvSVRvpJwlkQ0BQhrNCI6z5LzIjdnuvEFgerjbhW8wiJcUijsnw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fabric-callback-forgerock-ids
      namespace: fabric-services-cde-preprod-k

