apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: architecture
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: venugosv/architecture
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: Architecture
  owner: venugosv
  lifecycle: experimental
