site_name: Architecture
site_url: https://archspecs.com/
repo_url: https://github.com/venugosv/architecture
nav:
    - Home: index.md
    - Solution Architecture & Design:
      - fabric:
          -Architectural Increments:
            - 042 - DCVV2 In-House: DCVV2.md
theme:
    name: material
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "_"
    - plantuml_markdown:
plugins:
  - search
  - techdocs-core
