name: sit
serviceAccount:
  email: cards-sit@anz-x-fabric-cde-np-ba0f52.iam.gserviceaccount.com
scheduling:
  replicas: 1
config:
  extauth: fakerock
tasks:
  - name: cards-integration-test-grpc
    type: kubernetes
    kubernetes:
      serviceAccount: cards
      istioSidecar: true
      automountServiceAccountToken: true
    image:
      repository: gcr.io/anz-x-fabric-np-641432/cards/cards-integration
    env:
      - name: TEST_CONFIG_FILE
        value: ./config/sit.yaml
    command:
      - "/bin/integration-cards.test"
      - "-test.v"
      - "-test.run"
      - "GRPC"
  - name: cards-integration-test-rest
    type: kubernetes
    kubernetes:
      serviceAccount: cards
      istioSidecar: true
      automountServiceAccountToken: true
    image:
      repository: gcr.io/anz-x-fabric-np-641432/cards/cards-integration
    env:
      - name: TEST_CONFIG_FILE
        value: ./config/sit.yaml
    command:
      - "/bin/integration-cards.test"
      - "-test.v"
      - "-test.run"
      - "REST"
