spec:
  port: 8080
  log:
    level: debug
    payloadDecider:
      client:
        - /fabric.service.entitlements.v1beta1.cardentitlementsapi/getentitledcard: true
        - /fabric.service.entitlements.v1beta1.cardentitlementsapi/listentitledcards: true
        - /fabric.service.eligibility.v1beta1.cardeligibilityapi/can: false
        - /gateway.visa.service.customerrules.v1.customerrulesapi/createcontrols: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/deletecontrols: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/getcontroldocument: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/listcontroldocuments: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/register: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/updateaccount: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/updatecontrols: true
      server:
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/list: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/block: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/query: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/remove: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/set: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/blockcard: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/querycontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/removecontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/setcontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/listcontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/transfercontrols: true
  entitlements:
    baseURL: http://entitlements.fabric-services-intpnv.svc.cluster.local:8080
  eligibility:
    baseURL: http://cards.fabric-services-cde-intpnv.svc.cluster.local:8080
  cardcontrols:
    baseURL: http://cardcontrols.fabric-services-cde-intpnv.svc.cluster.local:8080
  auth:
    issuers:
      - name: "https://identity-services-pnv-int-gw.apps-int.x.gcpnp.anz/am/oauth2/customer"
        jwksUrl: "https://identity-services-pnv-int-gw.apps-int.x.gcpnp.anz/am/oauth2/customer/connect/jwk_uri"
        cacheTTL: 30m
  visa:
    baseURL: https://service-virtualisation-pnv.fabric.gcpnp.anz/vctc
    clientIDEnvKey: projects/517918342546/secrets/apic-ecom-client-id-np/versions/latest
    maxRetries: 3
  ctm:
    baseURL: https://service-virtualisation-pnv.fabric.gcpnp.anz/daw
    clientIDEnvKey: projects/517918342546/secrets/apic-corp-client-id-np/versions/latest
    maxRetries: 3
  commandCentre:
    env: intpnv
  ocv:
    baseURL: https://service-virtualisation-pnv.fabric.gcpnp.anz/ocv
    clientIDEnvKey: projects/517918342546/secrets/apic-corp-client-id-np/versions/latest
    enableLogging: true
    maxRetries: 3
  vault:
    vaultAddress: https://service-virtualisation-pnv.fabric.gcpnp.anz/vault
    authRole: gcpiamrole-fabric-decode.common
    authPath: v1/auth/gcp-fabric
    namespace: eaas-test
    zone: corp
    metadataAddress: http://metadata.google.internal
    tokenLifetime: 5m
    tokenErrorRetryFirstTime: 500ms
    tokenErrorRetryMaxTime: 5m
    tokenRenewBuffer: 2m
  visaGateway:
    baseURL: http://visa-gateway.fabric-services-cde-intpnv.svc.cluster.local:9060
  featureToggles:
    rpc:
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/block: true
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/query: true
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/remove: true
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/set: true
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/list: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/blockcard: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/querycontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/removecontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/setcontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/listcontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/transfercontrols: true
    features:
      - TCT_ATM_WITHDRAW: true
      - TCT_E_COMMERCE: true
      - TCT_CONTACTLESS: true
      - MCT_GAMBLING: true
  auditlog:
    name: fabric-cardcontrols
    domain: fabric.gcp.anz
    provider: fabric
    pubsub:
      projectID: anz-x-fabric-np-641432
      topicID: fabric-auditlog-intpnv
ops:
  port: 8082
  opentelemetry:
    metrics:
      exporter: collector
    trace:
      exporter: collector
    exporters:
      collector:
        host: otelcol-otlp-grpc-preprod-ebbg6xakwa-ts.a.run.app:443
        secure: true
