spec:
  port: 8080
  log:
    level: info
    payloadDecider:
      client:
        - /fabric.service.entitlements.v1beta1.cardentitlementsapi/getentitledcard: true
        - /fabric.service.entitlements.v1beta1.cardentitlementsapi/listentitledcards: true
        - /fabric.service.eligibility.v1beta1.cardeligibilityapi/can: false
        - /gateway.visa.service.customerrules.v1.customerrulesapi/createcontrols: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/deletecontrols: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/getcontroldocument: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/listcontroldocuments: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/register: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/updateaccount: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/updatecontrols: true
      server:
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/list: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/block: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/query: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/remove: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/set: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/blockcard: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/querycontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/removecontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/setcontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/listcontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/transfercontrols: true
  auth:
    issuers:
      - name: fakerock.preprod.fabric.gcpnp.anz
        jwksUrl: "https://fakerock-preprod.fabric.gcpnp.anz/.well-known/jwks.json"
        cacheTTL: 30m
      - name: "https://identity-services-np-int-gw.apps-int.x.gcpnp.anz/am/oauth2/customer"
        jwksUrl: "https://identity-services-np-int-gw.apps-int.x.gcpnp.anz/am/oauth2/customer/connect/jwk_uri"
        cacheTTL: 30m
      - name: "https://identity-services-sit-int-gw.apps-int.x.gcpnp.anz/am/oauth2/customer"
        jwksUrl: "https://identity-services-sit-int-gw.apps-int.x.gcpnp.anz/am/oauth2/customer/connect/jwk_uri"
        cacheTTL: 30m
      - name: "https://identity-services-np-int-gw.apps-int.x.gcpnp.anz/am/oauth2/system"
        jwksUrl: "https://identity-services-np-int-gw.apps-int.x.gcpnp.anz/am/oauth2/system/connect/jwk_uri"
        cacheTTL: 30m
      - name: "https://identity-services-sit-int-gw.apps-int.x.gcpnp.anz/am/oauth2/system"
        jwksUrl: "https://identity-services-sit-int-gw.apps-int.x.gcpnp.anz/am/oauth2/system/connect/jwk_uri"
        cacheTTL: 30m
  auditlog:
    name: fabric-cards
    domain: fabric.gcp.anz
    provider: fabric
    pubsub:
      projectID: anz-x-cosmos-dev-7252fe
      topicID: cosmos-audit
  commandCentre:
    env: preprod
  ctm:
    baseURL: http://apiqa.corp.dev.anz/daw
    clientIDEnvKey: projects/517918342546/secrets/apic-corp-client-id-np/versions/latest
    maxRetries: 3
  eligibility:
    baseURL: http://cards.fabric-services-cde-preprod.svc.cluster.local:8080
  cardcontrols:
    baseURL: http://cardcontrols.fabric-services-cde-preprod.svc.cluster.local:8080
  entitlements:
    baseURL: http://entitlements.fabric-services-preprod.svc.cluster.local:8080
  forgerock:
    baseURL: https://identity-services-np-int-gw.apps-int.x.gcpnp.anz
    clientID: fabric-cardcontrols
    clientSecretKey: projects/517918342546/secrets/cardcontrols-forgerock-secret-np/versions/latest
  visa:
    baseURL: http://apiqa.ecom.dev.anz/vctc
    clientIDEnvKey: projects/517918342546/secrets/apic-ecom-client-id-np/versions/latest
    maxRetries: 3
  visaGateway:
    baseURL: http://visa-gateway.fabric-services-cde-preprod.svc.cluster.local:8080
  vault:
    vaultAddress: http://eaas.adp.np.sec.gcpnp.anz
    authRole: gcpiamrole-fabric-decode.common
    authPath: v1/auth/gcp-fabric
    namespace: eaas-test
    zone: corp
    metadataAddress: http://metadata.google.internal
    tokenLifetime: 15m
    tokenErrorRetryFirstTime: 500ms
    tokenErrorRetryMaxTime: 5m
    tokenRenewBuffer: 2m
  featureToggles:
    rpc:
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/block: true
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/query: false
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/remove: false
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/set: false
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/list: false
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/blockcard: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/querycontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/removecontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/setcontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/listcontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/transfercontrols: true
    features:
      - TCT_ATM_WITHDRAW: true
      - TCT_E_COMMERCE: true
      - TCT_CONTACTLESS: true
      - MCT_GAMBLING: true
      - TCT_CROSS_BORDER: true
      - GCT_GLOBAL: true
      - FORGEROCK_SYSTEM_LOGIN: true
ops:
  port: 8082
  opentelemetry:
    metrics:
      exporter: collector
    trace:
      exporter: collector
    exporters:
      collector:
        host: otelcol-otlp-grpc-preprod-ebbg6xakwa-ts.a.run.app:443
        secure: true
