spec:
  port: 8080
  log:
    level: info
    payloadDecider:
      client:
        - /fabric.service.entitlements.v1beta1.cardentitlementsapi/getentitledcard: true
        - /fabric.service.entitlements.v1beta1.cardentitlementsapi/listentitledcards: true
        - /fabric.service.eligibility.v1beta1.cardeligibilityapi/can: false
      server:
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/list: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/block: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/query: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/remove: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/set: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/blockcard: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/querycontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/removecontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/setcontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/listcontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/transfercontrols: true
  auth:
    issuers:
      - name: "https://identity-services-prod-int-gw.apps-int.x.gcp.anz/am/oauth2/system"
        jwksUrl: "https://identity-services-prod-int-gw.apps-int.x.gcp.anz/am/oauth2/system/connect/jwk_uri"
        cacheTTL: 30m
      - name: "https://identity-services-prod-int-gw.apps-int.x.gcp.anz/am/oauth2/customer"
        jwksUrl: "https://identity-services-prod-int-gw.apps-int.x.gcp.anz/am/oauth2/customer/connect/jwk_uri"
        cacheTTL: 30m
  auditlog:
    name: fabric-cards
    domain: fabric.gcp.anz
    provider: fabric
    pubsub:
      projectID: anz-x-cosmos-prod-ccc3bd
      topicID: cosmos-audit
  commandCentre:
    env: production
  ctm:
    baseURL: http://api.corp.apps.anz/daw
    clientIDEnvKey: projects/791972436961/secrets/apic-corp-client-id-prod/versions/latest
    maxRetries: 3
  eligibility:
    baseURL: http://cards.fabric-services-cde-prod.svc.cluster.local:8080
  entitlements:
    baseURL: http://entitlements.fabric-services-prod.svc.cluster.local:8080
  forgerock:
    baseURL: https://identity-services-prod-int-gw.apps-int.x.gcp.anz
    clientID: fabric-cardcontrols
    clientSecretKey: projects/791972436961/secrets/cardcontrols-forgerock-secret-prod/versions/latest
  visa:
    baseURL: http://api.ecom.apps.anz/vctc
    clientIDEnvKey: projects/791972436961/secrets/apic-ecom-client-id-prod/versions/latest
    maxRetries: 3
  visaGateway:
    baseURL: http://visa-gateway.fabric-services-cde-prod.svc.cluster.local:8080
  vault:
    vaultAddress: http://eaas.adp.prd.sec.gcp.anz
    authRole: gcpiamrole-fabric-decode.common
    authPath: v1/auth/gcp-fabric
    namespace: eaas-prod
    zone: corp
    metadataAddress: http://metadata.google.internal
    tokenLifetime: 15m
    tokenErrorRetryFirstTime: 500ms
    tokenErrorRetryMaxTime: 5m
    tokenRenewBuffer: 2m
  featureToggles:
    rpc:
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/block: true
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/query: false
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/remove: false
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/set: false
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/list: false
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/blockcard: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/querycontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/removecontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/setcontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/listcontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/transfercontrols: true
    features:
      - TCT_ATM_WITHDRAW: true
      - TCT_E_COMMERCE: true
      - TCT_CONTACTLESS: true
      - MCT_GAMBLING: true
      - TCT_CROSS_BORDER: true
      - GCT_GLOBAL: true
      - FORGEROCK_SYSTEM_LOGIN: true
ops:
  port: 8082
  opentelemetry:
    metrics:
      exporter: collector
    trace:
      exporter: stackdriver
    exporters:
      stackdriver:
        projectID: anz-x-fabric-prod-d8873d
