spec:
  port: 8080
  log:
    level: debug
    payloadDecider:
      client:
        - /fabric.service.entitlements.v1beta1.cardentitlementsapi/getentitledcard: true
        - /fabric.service.entitlements.v1beta1.cardentitlementsapi/listentitledcards: true
        - /fabric.service.eligibility.v1beta1.cardeligibilityapi/can: false
        - /gateway.visa.service.customerrules.v1.customerrulesapi/createcontrols: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/deletecontrols: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/getcontroldocument: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/listcontroldocuments: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/register: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/updateaccount: true
        - /gateway.visa.service.customerrules.v1.customerrulesapi/updatecontrols: true
      server:
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/list: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/block: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/query: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/remove: true
        - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/set: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/blockcard: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/querycontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/removecontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/setcontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/listcontrols: true
        - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/transfercontrols: true
  entitlements:
    baseURL: http://fabric-card-stub.fabric-services-cde-st.svc.cluster.local:9060
  eligibility:
    baseURL: http://cards.fabric-services-cde-st.svc.cluster.local:8080
  cardcontrols:
    baseURL: http://cardcontrols.fabric-services-cde-st.svc.cluster.local:8080
  auth:
    issuers:
      - name: fakerock.st.fabric.gcpnp.anz
        jwksUrl: "https://fakerock-st.fabric.gcpnp.anz/.well-known/jwks.json"
        cacheTTL: 30m
  visa:
    baseURL: http://fabric-card-stub.fabric-services-cde-st.svc.cluster.local:9070/vctc
    clientIDEnvKey: apic-ecom-client-id-np
    maxRetries: 3
  visaGateway:
    baseURL: http://visa-gateway.fabric-services-cde-st.svc.cluster.local:8080
  ctm:
    baseURL: http://fabric-card-stub.fabric-services-cde-st.svc.cluster.local:9070/ctm
    clientIDEnvKey: apic-corp-client-id-np
    maxRetries: 3
  commandCentre:
    env: st
  ocv:
    baseURL: http://fabric-card-stub.fabric-services-cde-st.svc.cluster.local:9070/ocv
    clientIDEnvKey: apic-corp-client-id-np
    enableLogging: true
    maxRetries: 3
  vault:
    vaultAddress: http://fabric-card-stub.fabric-services-cde-st.svc.cluster.local:9070/vault
    authRole: gcpiamrole-fabric-encdec.common
    authPath: v1/auth/gcp-fabric
    namespace: eaas-test
    zone: corp
    overrideServiceEmail: fabric@anz.com
    noGoogleCredentialsClient: true
    tokenLifetime: 5m
    tokenErrorRetryFirstTime: 500ms
    tokenErrorRetryMaxTime: 5m
    tokenRenewBuffer: 2m
  forgerock:
    baseURL: http://fabric-card-stub.fabric-services-cde-st.svc.cluster.local:9070/forgerock/
    clientID: fabric-cardcontrols
    clientSecretKey: cardcontrols-forgerock-secret-np
  featureToggles:
    rpc:
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/block: true
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/query: true
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/remove: true
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/set: true
      - /fabric.service.cardcontrols.v1beta1.cardcontrolsapi/list: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/blockcard: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/querycontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/removecontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/setcontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/listcontrols: true
      - /fabric.service.cardcontrols.v1beta2.cardcontrolsapi/transfercontrols: true
    features:
      - TCT_ATM_WITHDRAW: true
      - TCT_E_COMMERCE: true
      - TCT_CONTACTLESS: true
      - MCT_GAMBLING: true
      - TCT_CROSS_BORDER: true
      - GCT_GLOBAL: true
      - FORGEROCK_SYSTEM_LOGIN: false
  auditlog:
    name: fabric-cardcontrols
    domain: fabric.gcp.anz
    provider: fabric
    pubsub:
      projectID: anz-x-fabric-np-641432
      topicID: fabric-auditlog-st
ops:
  port: 8082
  opentelemetry:
    metrics:
      exporter: collector
    trace:
      exporter: collector
    exporters:
      collector:
        host: otelcol-otlp-grpc-preprod-ebbg6xakwa-ts.a.run.app:443
        secure: true
