apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fabric-callback-forgerock-ids
  namespace: fabric-services-cde-sit
spec:
  encryptedData:
    FORGEROCK_CLIENT_SECRET: AgCa6TpGu9GzuJyq2YMmM6QHlYnQtxNrGU5Q4rfN5YLkTSEJLSZmwWU5lftKx20A9dNdFL7GjcL6/ynGbfKsq6iBIdGuWjwUvqVXpRdQM7nW0TOx88vQgpwcn3q2UaZG1N9WsnRhDMZhZn+nEuZH+xLCDPix6CYratK9ou0C4zNWK50YdUr1OVG9UrQunyOLZ4nVL8plZ8QoOWdIiD6VCMlK/anQznaPq6dgDEWHcSK5K656n/AYaPP/iVGSbWaKoqCZyCnizMZDC6k8NlL5R9vNrIWvlxTN44+MJyPwuwP9TjzQhFOh8Pn/Z28HtmO66cb7zSfSnpT7hBVutR5okbVEPf4JluKg4l7SR+reLELHGvjckIt5WV1dQ6G+DsGN+/lMsgYknrgIbIBKB3FAotJffhyYNvgt1BD4FOCyFzc5LU8PMp0yfutYv/VRb+P/XUioMUi8EeQk1jzpwMtQIatypy/G65Nvi/FJIpZKpUr/w9ibHWocd5X6I1cU4pybzr1ePMegAK5qo5OwMv82bRvMLKyjduPCsW2N608/xMgUfQsgAUNVIK/k0eMSizi0aIpn0bwUQPSpSYxmnIFg29H71SAZ37pKpxb2jVlHr6XGW20KIRSksY2UilbJyl2Z+N4JATAyydNHlMEOQsAD/wf5X7xUga9UoUg1rWHnX5bxlhdxo8w5QoxOsJ0YOARENtDqp+8Km0a8xUOKJA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fabric-callback-forgerock-ids
      namespace: fabric-services-cde-sit

