apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-card-stub
  namespace: fabric-services-cde-st
  labels:
    run: fabric-card-stub
    app: fabric-card-stub
    app.kubernetes.io/managed-by: hand
    app.kubernetes.io/name: fabric-card-stub
    ci_group: Fabric
    ci_name: ANZx-Platform
    confidentiality: confidential
    integrity: trusted
    name: fabric-card-stub
    trustlevel: high
spec:
  selector:
    matchLabels:
      app: fabric-card-stub
  replicas: 1
  template:
    metadata:
      labels:
        run: fabric-card-stub
        app: fabric-card-stub
        app.kubernetes.io/managed-by: hand
        app.kubernetes.io/name: fabric-card-stub
        ci_group: Fabric
        ci_name: ANZx-Platform
        confidentiality: confidential
        integrity: trusted
        name: fabric-card-stub
        trustlevel: high
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodepool-name
                    operator: In
                    values:
                      - business-services
      containers:
        - name: fabric-card-stub
          image: gcr.io/anz-x-fabric-np-641432/cards/stub:${_FAB_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 9070
              name: http
            - containerPort: 9060
              name: grpc
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
      nodeSelector:
        nodepool-name: business-services
      serviceAccountName: cards
      automountServiceAccountToken: true
