---
# Source: catalog-info/templates/catalog-info.yaml
# This file is managed via anzx/fabric-actions. Do not copy or edit this file directly.
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cards
  description: Cards - An interface for Card Activation, Select PIN & Replacement. Provides a powerful and convenient way for cardholders to track and manage all payment activity on enrolled accounts and tokens
  tags:
    - golang
  links:
    - title: Slack
      url: slack://channel?id=C011QKDCGTB
      icon: Chat
    - title: Splunk
      url: https://anzx.splunkcloud.com/en-GB/app/search/search?q=search%20index%3D%22fabric_events_nonprod%22%20container_name%3Dcards&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=-30m%40m&latest=now&sid=1643770560.60221_CD04F90B-DFD6-4A22-BF34-06D82B207118
      icon: Link
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: venugosv/cards
    sonarqube.org/project-key: ghb:fabric-cards
    atlas/app-name: ANZx::Fabric::Cards
    backstage.io/kubernetes-label-selector: app=cards
