site_name: Architecture Specs
site_url: https://archspecs.com/
repo_url: https://github.com/venugosv/cards
nav:
    - Overview: docs/cards/component/index.md
    - Design:
      - DCVV2: docs/cards/component/Design/dcvv2.md
theme:
    name: material
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "_"
    - plantuml_markdown:
plugins:
  - search
  - techdocs-core
