apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fabric-cardcontrols-apic-client-ids
  namespace: fabric-services-cde-sit-k
spec:
  encryptedData:
    SPEC_CTM_CLIENTID: AgBE8tfhzD8+uFUmNdrIU+PPCCc2LsldV2Fu55YuwZNHnesEqxi+dh/cXID79rFq/inAIF+u5TU5LCIGi9ogMFEj1rJvJzX2qZ8+D8mUGF2NW6iGMFO30613GeQQP35FzkxTzEsVR0g7JctvVvyaxd6jAfUxWuzHEANC98nFaQuGa02Q/gIqGGg1JpbJrkFhgC3xUUfW+I+Em0P9+fCbhROSc6yj36SQsslI9bV49Issv3bpezqGw8VpfGM8DUQhvdtJl0q4LGmgNlviwRMnfN7jnQ0UzugwZPq4yIQAt6udvBbcVPJg8zY93nlWgg/fl9BBB+8Upzb+H6ArVhod2Tg6HykuTMXCxPPW8xPIcZUQzENIDxi/cg+3t74s0L8yKlqXw5oGZVX2zt58buMaT2GGpZ2Zz/J42c8TbVd+61TWk8fwuGC2wQqQ30lgZRANhMOMzPNVr9aLVFrcoyfoTAB5eG+5qaBHH4XVUuD4EdLdiV7LhwxlIBps3XhqxX5lZep7V/oW1djuXi3qzZ8oppHj6dzuHI+F2wrl9XZXgi/4qMmW4918eWcQv1DrFX3mPU6j0UndP6ZxG1xK5KwsMQLf0kQtzYq2OulkUK2SI/7/ptFWvidGDsFB5ivyTkCfTLA6yF1dRFY3qkbZEUFLa3X3YgYDVcx+SdL3mituXtgQt+hVt8e9AmJcFli4x5LxkgN0S8kXgCLr6O9MMKQTplqv33kGBJk5tT1xm8j6ocPOJcczr8Q=
    SPEC_VISA_CLIENTID: AgBN1RwJ8M/Rn/rHcsCOReUeZZyKVZadLz/M51sG4NmvRsntEKiTRQJCgTDHzugLASufo8TIMcUJm4GEtEsxlTYQWnEc5iq+IGBFFH+IaLhZb4amqGhObKuzmltyJutpXnfe6a2Cj98ZZZAWFq8IMRRM+w0HwI7xNRWjCgE1JNWdx+T7rE5OEzk9MTp+Z0WqDqhx05CjjXA9jm93tJn1wtxoQCw/OKjGtZ6TsdmFvqpBHXuA/2yLvp/78IofbF1kQhu3neIbHzDIOjCsMCbLZ8kO+YkB9V5D+LTMyfZDwYPyGnrlTXs3nTOq81FrQVahxvwmhdb9q+gf3VnSDRK+EjgzX83V2tDTZysZsYVo+gFswW84b6T0RueRswUgVXs0d0We45SWhfJc+9xh8wPXJR/VSe8XbdXR6XZLr1vnfgU2sFbkPsT+o526kP/X/XDbqQk0AzBp8diDNG2YwULRNn0BQ8PPW4AxwlBpCJ1oIF3KVTyUn1qXvGWASOs8uBziK1tHWqbDjG9aICh+OctBDdnLfKC7dc8j/rFBkCbOsWr9DD6MDoj84Rq640z6Zi/JIXMdUSlU1JpCwVoUfQpiyQbWMOHrqlEUvEd2IOqr7qQohqWUEYfaDpH7YPv9HrM1JEGtFajUPgZs8MYmu0830ud7OviVv2JpyINXL5boTh4qnv8glVB6k30njp5wyfGkJ7MvwkWgNRp+z2Bau5Cxrn7OP/v1gwYPRs5onMmElwBFF/3p4Sc=
  template:
    metadata:
      creationTimestamp: null
      name: fabric-cardcontrols-apic-client-ids
      namespace: fabric-services-cde-sit-k

